#!/usr/bin/env bash
# Regenerate constraints.txt — the set of versions this project was last known to
# work with, in every corner of the tree it does not declare itself.
#
# pyproject.toml declares INTENT ("litellm", "mcp>=1.2,<2"), and deliberately keeps
# it loose: this is a local-first project people install from a checkout, and a hard
# pin on every transitive package would fight the one choice that actually matters
# on their machine — which torch build they want. But loose intent means the install
# a bug report describes is not the install anyone else gets, and it means a
# transitive release can break a checkout that nobody touched.
#
# A CONSTRAINTS file (not a requirements file) is the middle: it says "if you install
# this package, install this version", and stays silent about packages nobody asked
# for. `--thin` still skips the voice; nothing here forces a download.
#
#   ./install.sh --pinned          install against these versions
#   pip install -c constraints.txt -e ".[voice,test]"    the same thing by hand
#
# Run this when you change a dependency in pyproject.toml, or deliberately to take
# transitive updates. Then run `./scripts/smoke_install.sh` and the test suite, and
# commit the two together — the file is a claim that this set works, and the claim
# is only worth what was run against it.
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT_DIR/constraints.txt"

command -v uv >/dev/null 2>&1 \
    || { printf 'Error: uv is not installed — see https://docs.astral.sh/uv/\n' >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# --universal: one file for Linux, macOS and Windows, and for every Python in
# requires-python — resolved with markers rather than to whatever this machine is.
# A constraints file that only holds on the machine that generated it is a trap for
# everybody else.
#
# These four extras are exactly what a default `./install.sh` resolves to (see the
# EXTRAS block there) — the install almost everybody gets, so it is the one whose
# versions are worth recording. The remaining extras (tts-qwen, forge-krea2, the Qt
# window) are not pinned here: each drags a different heavy stack, and pinning stacks
# nobody has installed is how a constraints file quietly becomes unsatisfiable.
# --python-version is the floor from requires-python, and it is load-bearing:
# --universal alone spans PLATFORMS but resolves for the interpreter running this
# script. Generated on a 3.12 machine without it, the file pinned numpy==2.5.2 —
# which requires >=3.12 — and every 3.11 install then failed to resolve at all,
# against a file whose entire purpose is to be the set that works. Raise this line
# when requires-python's floor rises.
printf '==> Resolving\n'
uv pip compile --universal --quiet --python-version 3.11 \
    --extra test --extra llm --extra voice --extra forge-local \
    -o "$TMP/full.txt" "$ROOT_DIR/pyproject.toml"

# Torch is left OUT, and so is everything that exists only because torch is there.
# pyproject says why at length: the default PyPI wheel is the CUDA one (4.5 GB), the
# CPU build from download.pytorch.org is 747 MB, and which of them belongs on a
# machine is that machine's call — install.sh asks. A pin here would answer it. It
# would also be answered WRONG: the version resolved from PyPI need not exist on the
# CPU index, and the failure would arrive as a fight between two indexes rather than
# as anything readable.
printf '==> Filtering out the torch stack (its build is the user'"'"'s choice)\n'
python3 - "$TMP/full.txt" "$TMP/pinned.txt" <<'PY'
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
# torch, its audio sibling, its GPU runtime, and its compiler.
unpinned = re.compile(r"^(torch|torchaudio|triton|nvidia-[a-z0-9-]+)([=<>!~ ;\[]|$)")

kept, dropped, skipping = [], [], False
for line in open(src).read().splitlines():
    if line.startswith("#") and not skipping:
        continue                      # uv's own header; this file writes its own
    if line.startswith(("    #", "  #")):
        if not skipping:
            kept.append(line)         # the "# via …" provenance under a kept pin
        continue
    skipping = bool(unpinned.match(line))
    (dropped if skipping else kept).append(line)

open(dst, "w").write("\n".join(kept).strip() + "\n")
print(f"    kept {sum(1 for l in kept if l and not l.startswith(' '))} pins, "
      f"left {len(dropped)} torch-stack packages unpinned")
PY

{
    cat <<'EOF'
# The versions YuriOS was last known to work with — a pip CONSTRAINTS file, not a
# requirements file: it fixes the version of anything that gets installed and asks
# for nothing on its own. `--thin` still skips the voice.
#
#   ./install.sh --pinned
#   pip install -c constraints.txt -e ".[test,llm,voice,forge-local]"
#
# Generated by ./scripts/pin_deps.sh from the extras a default install resolves to,
# universally (all three platforms, every Python in requires-python) — do not hand-
# edit; regenerate. torch, torchaudio, triton and the nvidia-* runtime are left out
# on purpose: which torch BUILD belongs on a machine (CPU, 747 MB vs CUDA, 4.5 GB) is
# that machine's call, install.sh asks it, and a pin here would answer it wrongly.
EOF
    cat "$TMP/pinned.txt"
} > "$OUT"

printf '==> Wrote %s\n' "${OUT#"$ROOT_DIR"/}"
printf '    Now run: ./scripts/smoke_install.sh && pytest\n'
