#!/usr/bin/env python3
"""Generate `docs/spec-map.md` — SPEC section → the code that implements it.

The `SPEC §n` comments already answer "which section governs this file?" — open
the file, read the docstring. They do not answer the reverse, "which code
implements §21?", without a repo-wide grep, and that is the direction you are
going in when the spec is what you have (a behaviour to change, a rule to check,
a review against the normative text).

So: derive it. This walks the same citations `tests/test_spec_citations.py`
keeps honest and writes the inverse index. Regenerate after moving code between
modules:

    python scripts/spec_map.py            # writes docs/spec-map.md
    python scripts/spec_map.py --check    # non-zero if it is out of date

Derived, never hand-edited — the citations are the source of truth, and a map
maintained by hand would be one more thing to drift.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "spec-map.md"

CITATION = re.compile(r"\bSPEC\s*§\s*(\d+(?:\.\d+)*)")
HEADING = re.compile(r"^##\s*§(\d+(?:\.\d+)*)\s*—\s*(.+?)\s*$", re.M)
SEARCHED = (("yurios", "*.py"), ("tests", "*.py"), ("scripts", "*.py"), ("web", "*.js"))
SKIP = ("__pycache__", "node_modules", "/dist/", "/vendor/", "test_spec_citations.py")


def _sort_key(section: str) -> tuple[int, ...]:
    return tuple(int(p) for p in section.split("."))


def collect() -> tuple[list[tuple[str, str]], dict[str, dict[str, int]]]:
    """(top-level sections in order, section -> {file: citation count})."""
    titles = HEADING.findall((ROOT / "SPEC.md").read_text(encoding="utf-8"))
    hits: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for sub, glob in SEARCHED:
        for path in sorted((ROOT / sub).rglob(glob)):
            if any(s in str(path) for s in SKIP):
                continue
            rel = str(path.relative_to(ROOT))
            for section in CITATION.findall(path.read_text(encoding="utf-8",
                                                           errors="ignore")):
                hits[section][rel] += 1
    return titles, hits


def render(titles: list[tuple[str, str]], hits: dict[str, dict[str, int]]) -> str:
    lines = [
        "# SPEC → code",
        "",
        "*Generated by `scripts/spec_map.py` from the `SPEC §n` citations in the tree —",
        "do not edit by hand. Regenerate after moving code between modules;",
        "`tests/test_spec_citations.py` keeps the citations themselves honest.*",
        "",
        "Which code implements a section. The reverse direction — which section governs",
        "a file — is in the file's own docstring. Counts are citation sites, so they",
        "rank by how much of a module the section actually governs; the sub-sections of",
        "a section are folded into it.",
        "",
        "| Section | Implemented in | Also cited by |",
        "|---|---|---|",
    ]
    for section, title in sorted(titles, key=lambda t: _sort_key(t[0])):
        merged: dict[str, int] = defaultdict(int)
        for cited, files in hits.items():
            if cited == section or cited.startswith(section + "."):
                for f, n in files.items():
                    merged[f] += n
        ranked = sorted(merged.items(), key=lambda kv: (-kv[1], kv[0]))
        code = [f for f, _ in ranked if f.startswith(("yurios/", "web/", "scripts/"))]
        tests = [f for f, _ in ranked if f.startswith("tests/")]
        primary = "<br>".join(f"`{f}`" for f in code[:4]) or "—"
        if len(code) > 4:
            primary += f"<br>*+{len(code) - 4} more*"
        secondary = "<br>".join(f"`{f}`" for f in tests[:3]) or "—"
        if len(tests) > 3:
            secondary += f"<br>*+{len(tests) - 3} more*"
        lines.append(f"| **§{section}** — {title} | {primary} | {secondary} |")
    lines += ["", f"*{sum(sum(f.values()) for f in hits.values())} citation sites "
                  f"over {len(hits)} sections.*", ""]
    return "\n".join(lines)


def audit(titles: list[tuple[str, str]], hits: dict[str, dict[str, int]]) -> int:
    """List citations that resolve to a section they probably do not mean.

    `tests/test_spec_citations.py` catches two failure modes: a `SPEC §n` that
    does not exist, and one that lands on a superseded stub. There is a third
    it cannot see — a citation that resolves perfectly, to the wrong section.
    `app/vaultgit.py` said `SPEC §6.5` for the Vault's commit rule; §6.5 exists
    and is *Desktop presence*. The number was the predecessor spec's and had
    lost its `B1` prefix, so every check passed.

    No test can decide that one: it is a question about meaning. What a machine
    *can* do is narrow where to look, and the signal that works is the odd
    package out — a section reached from one package by a single site while
    every other citer of it lives elsewhere. That is what a citation inherited
    from another build's numbering looks like, and it is how the second
    instance (`app/memory/summarise.py`, "Rolling summarisation (SPEC §7.3)",
    where §7.3 is Guardrails) was found.

    A review list, not a verdict — most rows below are correct citations that
    simply happen to be lonely. Run it after moving code between packages, and
    read the pairs.
    """
    named = dict(titles)
    flagged = 0
    print("Citations worth a second look — the odd package out of a section's "
          "citers.\nMost are fine; read the pairing, not the count.\n")
    for section in sorted(hits, key=_sort_key):
        files = hits[section]
        if len(files) < 4:
            continue
        # `yurios/` only: a package is a meaningful grouping there, and
        # nowhere else. `web/` is one frontend and `tests/` is flat, so
        # including either turns every section into an "outlier".
        packages: dict[str, list[str]] = defaultdict(list)
        for rel in files:
            parts = pathlib.Path(rel).parts
            if parts[0] != "yurios":
                continue
            packages[parts[1] if len(parts) > 2 else "top"].append(rel)
        owned_total = sum(len(v) for v in packages.values())
        if len(packages) < 2 or owned_total < 4:
            continue
        for package, owned in sorted(packages.items()):
            if len(owned) != 1 or owned_total - 1 < 3:
                continue
            parent = section.split(".")[0]
            title = named.get(parent, "")
            where = (f"§{section}, under §{parent} — {title}" if "." in section
                     else f"§{section} — {title}")
            print(f"  {owned[0]}")
            print(f"    cites {where}")
            print(f"    …alone; the other {owned_total - 1} in yurios/ are "
                  f"{', '.join(sorted(set(packages) - {package}))}\n")
            flagged += 1
    print(f"{flagged} flagged.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if docs/spec-map.md is out of date")
    ap.add_argument("--audit", action="store_true",
                    help="list citations that may resolve to the wrong section")
    args = ap.parse_args()
    titles, hits = collect()
    if args.audit:
        return audit(titles, hits)
    body = render(titles, hits)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != body:
            print(f"{OUT.relative_to(ROOT)} is out of date — "
                  f"run: python scripts/spec_map.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
