#!/usr/bin/env python3
"""Generate `docs/spec-map.md` — SPEC section → the code that implements it.

The `SPEC §n` comments already answer "which section governs this file?" — open
the file, read the docstring. They do not answer the reverse, "which code
implements §21?", without a repo-wide grep, and that is the direction you are
going in when the spec is what you have (a behaviour to change, a rule to check,
a review against the normative text).

So: derive it. This walks the same citations `tests/test_spec_citations.py`
keeps honest and writes the inverse index. Regenerate after moving code between
modules:

    python scripts/spec_map.py            # writes docs/spec-map.md
    python scripts/spec_map.py --check    # non-zero if it is out of date

Derived, never hand-edited — the citations are the source of truth, and a map
maintained by hand would be one more thing to drift.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "spec-map.md"

CITATION = re.compile(r"\bSPEC\s*§\s*(\d+(?:\.\d+)*)")
HEADING = re.compile(r"^##\s*§(\d+(?:\.\d+)*)\s*—\s*(.+?)\s*$", re.M)
SEARCHED = (("yurios", "*.py"), ("tests", "*.py"), ("scripts", "*.py"), ("web", "*.js"))
SKIP = ("__pycache__", "node_modules", "/dist/", "/vendor/", "test_spec_citations.py")


def _sort_key(section: str) -> tuple[int, ...]:
    return tuple(int(p) for p in section.split("."))


def collect() -> tuple[list[tuple[str, str]], dict[str, dict[str, int]]]:
    """(top-level sections in order, section -> {file: citation count})."""
    titles = HEADING.findall((ROOT / "SPEC.md").read_text(encoding="utf-8"))
    hits: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for sub, glob in SEARCHED:
        for path in sorted((ROOT / sub).rglob(glob)):
            if any(s in str(path) for s in SKIP):
                continue
            rel = str(path.relative_to(ROOT))
            for section in CITATION.findall(path.read_text(encoding="utf-8",
                                                           errors="ignore")):
                hits[section][rel] += 1
    return titles, hits


def render(titles: list[tuple[str, str]], hits: dict[str, dict[str, int]]) -> str:
    lines = [
        "# SPEC → code",
        "",
        "*Generated by `scripts/spec_map.py` from the `SPEC §n` citations in the tree —",
        "do not edit by hand. Regenerate after moving code between modules;",
        "`tests/test_spec_citations.py` keeps the citations themselves honest.*",
        "",
        "Which code implements a section. The reverse direction — which section governs",
        "a file — is in the file's own docstring. Counts are citation sites, so they",
        "rank by how much of a module the section actually governs; the sub-sections of",
        "a section are folded into it.",
        "",
        "| Section | Implemented in | Also cited by |",
        "|---|---|---|",
    ]
    for section, title in sorted(titles, key=lambda t: _sort_key(t[0])):
        merged: dict[str, int] = defaultdict(int)
        for cited, files in hits.items():
            if cited == section or cited.startswith(section + "."):
                for f, n in files.items():
                    merged[f] += n
        ranked = sorted(merged.items(), key=lambda kv: (-kv[1], kv[0]))
        code = [f for f, _ in ranked if f.startswith(("yurios/", "web/", "scripts/"))]
        tests = [f for f, _ in ranked if f.startswith("tests/")]
        primary = "<br>".join(f"`{f}`" for f in code[:4]) or "—"
        if len(code) > 4:
            primary += f"<br>*+{len(code) - 4} more*"
        secondary = "<br>".join(f"`{f}`" for f in tests[:3]) or "—"
        if len(tests) > 3:
            secondary += f"<br>*+{len(tests) - 3} more*"
        lines.append(f"| **§{section}** — {title} | {primary} | {secondary} |")
    lines += ["", f"*{sum(sum(f.values()) for f in hits.values())} citation sites "
                  f"over {len(hits)} sections.*", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if docs/spec-map.md is out of date")
    args = ap.parse_args()
    body = render(*collect())
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != body:
            print(f"{OUT.relative_to(ROOT)} is out of date — "
                  f"run: python scripts/spec_map.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
